version: '3.9'
services:
  # Api endpoint for sending notifications
  notifications:
    build:
      context: '.'
    environment:
      - EMAIL_PROVIDER=smtp
      - SMTP_HOST=mailcatcher
      - SMTP_PORT=1025
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - '8080:8080'
    volumes:
      - ./:/notification-api
    command: gunicorn app:app -b 0.0.0.0:8080 -w 2 --reload
    depends_on:
      - mailcatcher

  # Worker that runs the queue jobs for redis
  queueworker:
    build:
      context: '.'
    environment:
      - EMAIL_PROVIDER=smtp
      - SMTP_HOST=mailcatcher
      - SMTP_PORT=1025
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    command: rq worker --url redis://redis:6379
    links:
      - redis

  # Redis queue for notifications
  redis:
    image: redis:alpine
    ports:
      - '8081:6379'
    command: 'redis-server --bind redis --maxmemory 256mb --maxmemory-policy allkeys-lru --appendonly yes'

  # Intercept and test email sending locally
  mailcatcher:
    image: dockage/mailcatcher:0.9.0
    ports:
      - '1025:1025'
      - '1080:1080'
