# Note that if/when Integration Tests are enabled, the build
# will be implicitly tested there and this may be obsolete.
name: Build Tests

on:
  push:
    branches: [main]
  pull_request:
    paths-ignore:
      - 'tofu/**'
      - 'docs/**'
      - '**/*.md'

# Cancel existing executions when new commits are pushed onto the branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      # Build each separately to help with debugging
      - name: Build web
        run: npm run build:web

      - name: Build collect
        run: npm run build:collect

      - name: Build migrate
        run: npm run build:migrate

      - name: Build notify
        run: npm run build:notify
