# Collects recen data from OMB website and saves the results to DB.
# Note that this only runs the recent updates and the full data collection
# and archive to S3 should be done separately.
#
# Runs on a schedule (see below)

name: Collect data (New)

on:
  # Unforutately, Github Actions does not support timezone setting
  # and only supports UTC.  This is unfortunate.
  # https://www.worldtimebuddy.com/utc-to-est-converter
  #
  # We want this to align with the config in src/config/index.ts and have
  # it run a few hours before the header cache time (currently 5AM New_York).
  # 6AM UTC = 2AM EDT
  schedule:
    - cron: '0 6 * * 1-6'
  workflow_dispatch:

env:
  AWS_REGION: 'us-west-2'
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ROLE_TO_ASSUME: 'collect'
  TOFU_TASK_DEFINITION_OUTPUT: 'collect_task_definition_arn'
  tf_actions_working_dir: 'tofu'

# Cancel existing executions when new commits are pushed onto the branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  collect:
    name: Collect data
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir }}

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
          unset-current-credentials: true

      - name: OpenTofu init
        id: init
        run: tofu init

      # NOTE: Needed to use the stdout output from the tofu commands to set the environment
      # variables. Otherwise GitHub Actions would put the wrong output into the environment
      # variables if i tried to do it directly.
      - name: Set task definition ARN
        id: aws_task_def_arn
        run: |
          tofu output --raw ${{ env.TOFU_TASK_DEFINITION_OUTPUT }}
      - name: Set task definition env
        run: |
          echo "AWS_TASK_DEF_ARN=${{ steps.aws_task_def_arn.outputs.stdout }}" >> "$GITHUB_ENV"

      - name: Set cluster ARN
        id: aws_ecs_cluster_arn
        run: |
          tofu output --raw ecs_cluster_arn
      - name: Set cluster env
        run: |
          echo "AWS_ECS_CLUSTER_ARN=${{ steps.aws_ecs_cluster_arn.outputs.stdout }}" >> "$GITHUB_ENV"

      - name: Set network config
        id: aws_run_task_network_config
        run: |
          tofu output --raw run_task_network_configuration_string
      - name: Set network config env
        run: |
          echo "AWS_NETWORK_CONFIG=${{ steps.aws_run_task_network_config.outputs.stdout }}" >> "$GITHUB_ENV"

      - name: Run ECS collect task
        shell: bash
        run: |
          aws ecs run-task --task-definition "${{ env.AWS_TASK_DEF_ARN }}" --cluster "${{ env.AWS_ECS_CLUSTER_ARN }}" --network-configuration "${{ env.AWS_NETWORK_CONFIG }}" --launch-type FARGATE --tags key=Name,value=apportionments-collect-new --overrides '{ "containerOverrides": [{ "command": ["build-collect/collect.js", "--new-records-only"] }]}'
