# Builds a new docker image, pushes image to ECR, and deploys new image to ECS
# Runs when a new release is released

name: Deploy to AWS

on:
  release:
    types: [released]
  workflow_dispatch:

env:
  AWS_REGION: 'us-west-2'
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_TASK_DEFINITION_FAMILY: 'apportionments-app'
  AWS_ECS_SERVICE: 'apportionments-app'
  AWS_ECS_CLUSTER: 'apportionments-app'
  tf_actions_working_dir: 'tofu'

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-actions-${{ github.repository_owner }}-${{ github.event.repository.name }}
          aws-region: ${{ env.AWS_REGION }}

      - name: OpenTofu init
        id: init
        working-directory: ${{ env.tf_actions_working_dir }}
        run: tofu init

      # NOTE: Needed to use the stdout output from the tofu commands to set the environment
      # variables. Otherwise GitHub Actions would put the wrong output into the environment
      # variables if i tried to do it directly.
      - name: Set Cloudfront ID
        id: aws_cloudfront_distribution_id
        working-directory: ${{ env.tf_actions_working_dir }}
        run: |
          tofu output --raw cloudfront_distribution_id
      - name: Set Cloudfront ID env
        working-directory: ${{ env.tf_actions_working_dir }}
        run: |
          echo "AWS_CLOUDFRONT_DISTRIBUTION_ID=${{ steps.aws_cloudfront_distribution_id.outputs.stdout }}" >> "$GITHUB_ENV"

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Extract metadata tags for Docker
        env:
          IMAGE_TAG: ${{ github.sha }}
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ github.event.repository.name }}
          tags: |
            # set latest tag for main branch
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            # set tag to the long commit code
            type=sha,format=long

      - name: Build and push Docker image
        env:
          VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN }}
          VITE_SENTRY_SCRIPT: ${{ secrets.VITE_SENTRY_SCRIPT }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}

      - name: Deploy to Amazon ECS
        run: aws ecs update-service --cluster ${{ env.AWS_ECS_CLUSTER }} --service ${{ env.AWS_ECS_SERVICE }} --force-new-deployment

      - name: Invalidate Cloudfront
        run: aws cloudfront create-invalidation --distribution-id ${{ env.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
