name: Push to ECR

on:
  #push:
  #  branches: ['main']

  workflow_dispatch:

env:
  AWS_REGION: "us-west-2"
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

jobs:
  push-container:
    runs-on: ubuntu-latest

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: "Create and Push Image"
        uses: tedivm/action-ecr-publish@v2.0.0
        with:
          aws_account_id: ${{ env.AWS_ACCOUNT_ID }}
          aws_region: ${{ env.AWS_REGION }}
          aws_role_to_assume: 'github-actions-${{ github.repository_owner }}-${{ github.event.repository.name }}'
