name: Deploy to AWS

on:
  push:
    branches: ['main']
    paths-ignore:
      - 'tofu/**'
      - 'docs/**'
      - '*.md'
      - '.*'
      - 'tests/**'

  workflow_dispatch:

env:
  AWS_REGION: 'us-west-2'
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_TASK_DEFINITION_FAMILY: 'apportionments-app'
  #AWS_ECS_SERVICE:
  #AWS_ECS_CLUSTER:

jobs:
  deploy:
    name: Push to ECR
    runs-on: ubuntu-latest

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-actions-${{ github.repository_owner }}-${{ github.event.repository.name }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # NOTE: Needed to use the stdout output from the tofu commands to set the environment
      # variables. Otherwise GitHub Actions would put the wrong output into the environment
      # variables if i tried to do it directly.
      - name: Get task definition file
        id: task-definition-file
        run: |
          aws ecs describe-task-definition --task-definition ${{ env.AWS_TASK_DEFINITION_FAMILY }} --query taskDefinition
      - name: Set task definition output
        id: task-definition
        run: |
          echo "TASK_DEF=${{ steps.task-definition-file.outputs.stdout}}" >> $GITHUB_OUTPUT

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ github.event.repository.name }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker buildx build --platform linux/amd64 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def-with-image
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ steps.task-definition.outputs.TASK_DEF }}
          container-name: ${{ env.AWS_TASK_DEFINITION_FAMILY }}
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def-with-image.outputs.task-definition }}
          force-new-deployment: true
          #service: ${{ env.AWS_ECS_SERVICE }}
          #cluster: ${{ env.AWS_ECS_CLUSTER }}
