name: Migrate database

on:
  push:
    branches: ['main']
    paths:
      - 'db/**'

  workflow_dispatch:

env:
  AWS_REGION: 'us-west-2'
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  tf_actions_working_dir: 'tofu'

jobs:
  deploy:
    name: Migrate database
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir }}

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      -  uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-actions-db-migration
          aws-region: ${{ env.AWS_REGION }}
          unset-current-credentials: true

      - name: OpenTofu init
        id: init
        run: tofu init

      - name: Test
        run: |
          {
            echo 'AWS_TASK_DEF_ARN<<EOF'
            tofu output --raw migrate_task_definition_arn
            echo EOF
          } >> "$GITHUB_ENV"

      - name: Run ECS database migration task
        shell: bash
        run: |
          aws ecs run-task --task-definition ${{ secrets.AWS_ECS_TASK_DEFINITION_ARN }} --cluster ${{ secrets.AWS_ECS_CLUSTER_ARN }} --network-configuration "${{ secrets.RUN_TASK_NETWORKING_CONFIGURATION }}" --launch-type FARGATE
