name: Migrate database

on:
  push:
    branches: ['main']
    paths:
      - 'db/**'

  workflow_dispatch:

env:
  AWS_REGION: "us-west-2"
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

jobs:
  deploy:
    name: Migrate database
    runs-on: ubuntu-latest

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: opentofu/setup-opentofu@v1

      - name: OpenTofu init
        id: init
        run: tofu init

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-actions-db-migration
          aws-region: ${{ env.AWS_REGION }}

      - name: Task defintion ARN
        run: |
          echo "AWS_TASK_DEFINITION_ARN=$(tofu output --raw migrate_task_definition_arn)" >> $GITHUB_ENV

      - name: ECS cluster ARN
        run: |
          echo "AWS_ECS_CLUSTER_ARN=$(tofu output --raw ecs_cluster_arn)" >> $GITHUB_ENV

      - name: Network configuration string
        run: |
          echo "AWS_NETWORK_CONFIGURATION_STRING=$(tofu output --raw run_task_network_configuration_string)" >> $GITHUB_ENV

      - name: Run ECS database migration task
        run: |
          aws ecs run-task --task-definition ${{ env.AWS_TASK_DEFINITION_ARN }} --cluster ${{ env.AWS_ECS_CLUSTER_ARN }} --network-configuration ${{ env.AWS_NETWORK_CONFIGURATION_STRING }} --launch-type FARGATE
